global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: load_balancer
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names: ["load_balancer"]
        type: "A"
        port: 8082

  - job_name: api
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names: ["api"]
        type: "A"
        port: 8080